//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.21 at 06:11:45 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "hu.skzs.multiproperties", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hu.skzs.multiproperties.base.model.schema;
